### ISSUE TITLE
`Last_Updated_Time` still stuck at 13/08 in `state_wise.csv`

### ISSUE THREAD

**Issue by siddhpant** [covid19india/data#1]
Related to covid19india/api#508, except now the delta data is being shown/updated correctly, but the date isn't updated.

![Screenshot_20210911-182806_Office.png](https://user-images.githubusercontent.com/25429745/132948602-9fbf2c6c-9c94-4348-ab34-a42b7d6090b5.png)

**Comment by Spiritman021** [comment]
Because they have updated their json data, json format, and hosted on different URL instead of https://api.covid19india.org/data.json
& https://data.covid19india.org/data.json .

here are the new URL for new data 👍 
https://data.covid19india.org/v4/min/timeseries.min.json --> Daily numbers across C,R,D and Tested per state (historical data).

 https://data.covid19india.org/v4/min/data.min.json --> Current day numbers across districts and states.

**Comment by siddhpant** [comment]
Please look at the issue. This is about the CSV endpoint listed in README, not about JSON timeseries and subdomain change. 

The CSV is from the latest endpoint, hence the issue here.

**Comment by shuklaayush** [comment]
Hey
The `Last_Updated_Time` field in the CSVs is deprecated. The website uses the `last_updated` field from https://data.covid19india.org/v4/data.json
